
parameters:

    locale: 'en'

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            # $talksUrl: 'https://api.joind.in/v2.1/events/6710/talks'
            $talksUrl: '%kernel.project_dir%/data/talks.json'

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Negotiation\Negotiator:
